on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: run the action
        id: hello
        uses: ./
        with:
          myInput: 'Jigyars'
      - name: output
        run: |
          echo ${{ steps.hello.outputs.memory}}
          echo "total memory output"
