name: 'My first action'
description: 'Cloud guru'
author: 'Me '
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
